//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _422_Zheltobryukh
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int CategoryID { get; set; }
        public System.DateTime Date { get; set; }
        public string Name { get; set; }
        public decimal Num { get; set; }
        public decimal Price { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual User User { get; set; }
    }
}
